import type { StandardSchemaV1 } from '@standard-schema/spec';
import { RouteContext } from './types.js';

/** Per-route metadata merged into the operation generated by `generateOpenApiDocument` */
export interface OpenApiOperationMeta {
  summary?: string;
  description?: string;
  operationId?: string;
  tags?: string[];
  deprecated?: boolean;
  responses?: Record<string, { description: string; content?: Record<string, { schema?: unknown }> }>;
}

/**
 * Per-route validation config. Accepts any schema implementing the
 * [Standard Schema](https://standardschema.dev) spec - zod (>=3.24), valibot,
 * arktype, effect/Schema, etc all work without a BlitzJS-specific adapter.
 */
export interface RouteSchema<
  TParams extends StandardSchemaV1 | undefined = StandardSchemaV1 | undefined,
  TQuery extends StandardSchemaV1 | undefined = StandardSchemaV1 | undefined,
  TBody extends StandardSchemaV1 | undefined = StandardSchemaV1 | undefined
> {
  params?: TParams;
  query?: TQuery;
  body?: TBody;
  openapi?: OpenApiOperationMeta;
}

/** Resolves to the schema's output type, or `Fallback` when no schema was given */
export type InferSchemaOutput<TSchema, Fallback> = TSchema extends StandardSchemaV1
  ? StandardSchemaV1.InferOutput<TSchema>
  : Fallback;

/** RouteContext with `params`/`query`/`body` replaced by their validated, typed output */
export type ValidatedRouteContext<TParams, TQuery, TBody> = Omit<RouteContext, 'params' | 'query' | 'body'> & {
  params: TParams;
  query: TQuery;
  body: TBody;
};

export type ValidatedHandlerFunction<TParams, TQuery, TBody> = (
  ctx: ValidatedRouteContext<TParams, TQuery, TBody>
) => unknown | Promise<unknown>;

export interface ValidationIssue {
  target: 'params' | 'query' | 'body';
  message: string;
  path?: ReadonlyArray<PropertyKey | StandardSchemaV1.PathSegment>;
}

async function runSchema(schema: StandardSchemaV1, value: unknown): Promise<StandardSchemaV1.Result<unknown>> {
  const result = schema['~standard'].validate(value);
  return result instanceof Promise ? await result : result;
}

/**
 * Validate a route's `params`/`query`/`body` against its `RouteSchema`,
 * mutating `ctx` in place with each schema's validated output on success.
 *
 * Must run before anything writes to `ctx.res` (headers/status/body) - once
 * a response has started, `writeStatus` for the `400` below has no effect.
 * Returns the collected issues, empty when validation passed.
 */
export async function applySchema(schema: RouteSchema, ctx: RouteContext): Promise<ValidationIssue[]> {
  const issues: ValidationIssue[] = [];

  if (schema.params) {
    const result = await runSchema(schema.params, ctx.params);
    if (result.issues) issues.push(...result.issues.map((i) => ({ target: 'params' as const, message: i.message, path: i.path })));
    else ctx.params = result.value as Record<string, string>;
  }

  if (schema.query) {
    const result = await runSchema(schema.query, ctx.query);
    if (result.issues) issues.push(...result.issues.map((i) => ({ target: 'query' as const, message: i.message, path: i.path })));
    else ctx.query = result.value as Record<string, string>;
  }

  if (schema.body) {
    const result = await runSchema(schema.body, ctx.body);
    if (result.issues) issues.push(...result.issues.map((i) => ({ target: 'body' as const, message: i.message, path: i.path })));
    else ctx.body = result.value;
  }

  return issues;
}
